name: CI/CD Pipeline

# Триггер на пуши и PR для всех нужных веток
on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main
      - development
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2. Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Устанавливаем зависимости (если requirements.txt нет, создадим пустой)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Прогоняем тесты
      - name: Run tests
        run: |
          if [ -d tests ]; then python -m unittest discover tests; else echo "No tests folder"; fi

      # 5. Обновляем документацию
      - name: Update docs
        run: |
          mkdir -p docs
          echo "Documentation updated" > docs/status.txt
