name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main
      - development
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Шаг 4: Запускаем тесты
      - name: Run tests
        run: |
          if [ -d tests ]; then python -m unittest discover tests; fi

      # Шаг 5: Обновляем документацию
      - name: Update docs
        run: |
          mkdir -p docs
          echo "Documentation updated" > docs/status.txt
